### ISSUE TITLE
Match tool (item) Condition

### ISSUE THREAD

**Issue by brachy84** [Leviathan143/More-Loot-Stuff#2]
This is actually a request but somehow that doesn't work for me. I want you to make a new condition that makes that specified loot will drop if mob was killed with specified tool (or item). Would be nice and helpfull for my modpack 😃

**Comment by Daomephsta** [comment]
> This is actually a request but somehow that doesn't work for me. 

An issue is exactly what I meant for you to make. Pull requests are quite a different thing, for quite a different purpose.
