### ISSUE TITLE
Check Blocks Under/Over Target

### ISSUE THREAD

**Issue by VinterNacht** [Leviathan143/More-Loot-Stuff#6]
Check the blocks that are over or under the target.  Ur example is to check the depth of the water where a bobber lands, but I'm sure creative souls could come up with other uses. (Is your target standing under glowstone? Chance to drop dust)

**Comment by Daomephsta** [comment]
Can you elaborate more on this? I'm not sure what you want. It doesn't sound like you want to just check the blocks directly over or under the target.

**Comment by VinterNacht** [comment]
I believe you are correct.  I'd like to be able to check if the (x-y# of blocks) under the bobber is water, for instance.  I'd also like to be able to check if the (x-y# of blocks) over the target contains or does not contain something, and potentially both on the same target.

A set of examples:
1 - Are the three blocks directly under the target water?
2 - Do the three blocks above the target contain at least one instance of glowstone?
3 - Are the three blocks directly under the target water AND do the three blocks directly above the target contain at least one instance of glowstone?
4 - Are the three blocks over the target glowstone (Must have three blocks of glowstone over the target)?
5 - Do the three blocks under the target NOT contain sand? (An inverse of the above logic)
6 - Is the first non-water/air block under the target sand?
7 - Is the first non-water/air block under the target NOT sand?
8 - The above two examples, only checking up instead of down.

Preferably multiple conditions should be able to be applied to a single target.
